apiVersion : apps/v1
kind: Deployment
metadata:
  name: finalapp 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finalapp
  template:
    metadata:
      labels:
        app: finalapp 
    spec:
      containers:
        - name: finalapp 
          image: kislay99.azurecr.io/finalapp
          ports:
          - containerPort: 80